/**
 * Export Utilities
 * 
 * Export data as PDF, CSV, and generate share links
 */

import jsPDF from 'jspdf'

/**
 * Export place data as PDF
 */
export function exportToPDF(place, options = {}) {
    const doc = new jsPDF()

    // Title
    doc.setFontSize(20)
    doc.text(place.canonical_name, 20, 20)

    // Metadata
    doc.setFontSize(12)
    doc.text(`Type: ${place.place_type}`, 20, 35)

    // Demographics
    doc.setFontSize(16)
    doc.text('Demographics', 20, 50)
    doc.setFontSize(12)

    let y = 60
    if (place.population?.value) {
        doc.text(`Population: ${place.population.value.toLocaleString()}`, 20, y)
        y += 10
    }
    if (place.literacy_rate?.value) {
        doc.text(`Literacy Rate: ${place.literacy_rate.value}%`, 20, y)
        y += 10
    }
    if (place.area_sq_km) {
        doc.text(`Area: ${place.area_sq_km.toLocaleString()} km²`, 20, y)
        y += 10
    }
    if (place.population_density) {
        doc.text(`Density: ${place.population_density.toLocaleString()}/km²`, 20, y)
        y += 10
    }

    // Industries
    if (place.major_industries && place.major_industries.length > 0) {
        y += 10
        doc.setFontSize(16)
        doc.text('Major Industries', 20, y)
        y += 10
        doc.setFontSize(12)
        place.major_industries.forEach(industry => {
            doc.text(`• ${industry}`, 25, y)
            y += 8
        })
    }

    // Footer
    doc.setFontSize(10)
    doc.text('Generated by BharatAtlas', 20, 280)
    doc.text(new Date().toLocaleDateString(), 20, 285)

    // Download
    doc.save(`${place.canonical_name.replace(/\s+/g, '_')}.pdf`)
}

/**
 * Export comparison data as CSV
 */
export function exportToCSV(places, metrics) {
    const headers = ['Place', ...metrics]
    const rows = places.map(place => [
        place.canonical_name,
        ...metrics.map(metric => getMetricValue(place, metric))
    ])

    const csv = [
        headers.join(','),
        ...rows.map(row => row.join(','))
    ].join('\n')

    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `comparison_${Date.now()}.csv`
    a.click()
    URL.revokeObjectURL(url)
}

function getMetricValue(place, metric) {
    switch (metric) {
        case 'Population':
            return place.population?.value || 'N/A'
        case 'Literacy Rate':
            return place.literacy_rate?.value || 'N/A'
        case 'Area':
            return place.area_sq_km || 'N/A'
        case 'Density':
            return place.population_density || 'N/A'
        default:
            return 'N/A'
    }
}

/**
 * Generate shareable link
 */
export function generateShareLink(type, data) {
    const baseUrl = window.location.origin
    const params = new URLSearchParams()

    switch (type) {
        case 'place':
            return `${baseUrl}/place/${data.place_id}`

        case 'comparison':
            params.set('places', data.places.map(p => p.place_id).join(','))
            return `${baseUrl}/compare?${params.toString()}`

        case 'search':
            params.set('q', data.query)
            return `${baseUrl}/explore?${params.toString()}`

        default:
            return baseUrl
    }
}

/**
 * Copy to clipboard
 */
export async function copyToClipboard(text) {
    try {
        await navigator.clipboard.writeText(text)
        return true
    } catch (error) {
        console.error('Failed to copy:', error)
        return false
    }
}

/**
 * Share on social media
 */
export function shareOnSocial(platform, url, text = '') {
    const encodedUrl = encodeURIComponent(url)
    const encodedText = encodeURIComponent(text)

    const urls = {
        twitter: `https://twitter.com/intent/tweet?url=${encodedUrl}&text=${encodedText}`,
        facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`,
        linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`
    }

    if (urls[platform]) {
        window.open(urls[platform], '_blank', 'width=600,height=400')
    }
}

/**
 * Generate embed code
 */
export function generateEmbedCode(url, width = 800, height = 600) {
    return `<iframe src="${url}" width="${width}" height="${height}" frameborder="0" allowfullscreen></iframe>`
}
